#!/bin/sh
#
# @name Flying V
#
# @type Standard plane
# @class Plane
#
# @output MAIN1 motor 1
# @output MAIN2 motor 2
# @output MAIN3 rudder 1
# @output MAIN4 rudder 2
# @output MAIN5 steering servo 
# @output MAIN6 elevon left 1
# @output MAIN7 elevon left 2 
# @output MAIN8 elevon left 3
#
# @output AUX1 brakes
# @output AUX2 retraction
# @output AUX3 Airdata trigger
# @output AUX4 elevon right 1
# @output AUX5 elevon right 2
# @output AUX6 elevon right 3

set VEHICLE_TYPE fw

if [ $AUTOCNF = yes ]
then
	
	# Default parameters for fixed wing UAVs.
	param set COM_POS_FS_DELAY 5
	param set COM_POS_FS_EPH 25
	param set COM_POS_FS_EPV 50
	param set COM_POS_FS_GAIN 0
	param set COM_POS_FS_PROB 1
	param set COM_VEL_FS_EVH 5

	# Kalman filter tuning gains
	param set EKF2_ARSP_THR 8
	param set EKF2_FUSE_BETA 1
	param set EKF2_GPS_CHECK 21
	param set EKF2_MAG_ACCLIM 0
	param set EKF2_MAG_YAWLIM 0
	param set EKF2_REQ_EPH 10
	param set EKF2_REQ_EPV 10
	param set EKF2_REQ_HDRIFT 0.5
	param set EKF2_REQ_SACC 1
	param set EKF2_REQ_VDRIFT 1.0

	# CHECK! 
	param set RTL_RETURN_ALT 100
	param set RTL_DESCEND_ALT 100
	param set RTL_LAND_DELAY -1

	# FW uses L1 distance for acceptance radius.
	# Set a smaller NAV_ACC_RAD for vertical acceptance distance.
	param set NAV_ACC_RAD 10

	# CHECK! 
	param set MIS_LTRMIN_ALT 25
	param set MIS_TAKEOFF_ALT 25


	# FW takeoff acceleration can easily exceed ublox GPS 2G default.
	param set GPS_UBX_DYNMODEL 8

	# USER PARAMETERS
	param set PWM_AUX_RATE 50
	param set PWM_RATE 50
	param set BAT_N_CELLS 6
	param set BAT_A_PER_V 65.02386
	param set BAT_V_DIV 19.12569

	# MAP AUXILIARY PARAMETERS 
	param set RC_MAP_AUX1 8
	param set RC_MAP_AUX2 7

fi

# Set MAV_TYPE (1 = std plane)
set MAV_TYPE 1

set MIXER flyingV
set MIXER_AUX flyingV

# Set PWM channels
set PWM_OUT 12345678
set PWM_AUX_OUT 123456
