#!/bin/sh
#
# @name Flying V
#
# @type Standard plane
# @class Plane
#
# @output MAIN1 motor 1
# @output MAIN2 motor 2
# @output MAIN3 elevator R
# @output MAIN4 elevon R 
# @output MAIN5 aileron R 
# @output MAIN6 rudder R 
# @output MAIN7 empty
# @output MAIN8 empty
#
# @output AUX1 brakes
# @output AUX2 retraction
# @output AUX3 Airdata trigger
# @output AUX4 steering servo 
# @output AUX5 elevator L 
# @output AUX6 elevon L 
# @output AUX7 aileron L 
# @output AUX8 rudder L 

set VEHICLE_TYPE fw

if [ $AUTOCNF = yes ]
then

	# ----------------------------------------------------
	#		 Default parameters for fixed wing UAVs.
	# ----------------------------------------------------
	param set COM_POS_FS_DELAY 5 	# Time grom GPS loss until failsafe is enabled
	param set COM_POS_FS_EPH 25
	param set COM_POS_FS_EPV 50
	param set COM_POS_FS_GAIN 0
	param set COM_POS_FS_PROB 1
	param set COM_VEL_FS_EVH 5
	param set COM_POSCTL_NAVL 0	 	# RC control after failsafe (1 = no RC control)

	# Kalman filter tuning gains
	param set EKF2_ARSP_THR 8
	param set EKF2_FUSE_BETA 1
	param set EKF2_GPS_CHECK 21
	param set EKF2_MAG_ACCLIM 0
	param set EKF2_MAG_YAWLIM 0
	param set EKF2_REQ_EPH 10
	param set EKF2_REQ_EPV 10
	param set EKF2_REQ_HDRIFT 0.5
	param set EKF2_REQ_SACC 1
	param set EKF2_REQ_VDRIFT 1.0 

	# CHECK! 
	param set RTL_RETURN_ALT 50  # Return altitude
	param set RTL_DESCEND_ALT 50  # Descent/Loiter altitude
	param set RTL_LAND_DELAY -1    # No land (loiter)

	# FW uses L1 distance for acceptance radius.
	# Set a smaller NAV_ACC_RAD for vertical acceptance distance.
	param set NAV_ACC_RAD 10    # Acceptance radius for waypoints
	param set NAV_LOITER_RAD 50  # Loiter radius

 	# Mission parameters
	param set MIS_LTRMIN_ALT 30  # Minimum loiter altitude 
	param set MIS_TAKEOFF_ALT 25 # Minimum takeoff altitude (for auto?)

	# FW takeoff acceleration can easily exceed ublox GPS 2G default.
	param set GPS_UBX_DYNMODEL 8

	# Geofence and failsafe
	param set GF_SOURCE 1 # GPS (independent of position estimation errors)
	param set GF_ACTION 0 # 1 = Warning 3 = Return mode
	param set GF_MAX_HOR_DIST 1000 # Maximum horizontal distance from home
	param set GF_MAX_VER_DIST 130 # Maximum vertical distance from home

	# ----------------------------------------------------
	#		 			PWM SETTINGS
	# ----------------------------------------------------
	# Individual limits
	param set PWM_MAIN_MIN1 900  # Engine 1
	param set PWM_MAIN_MIN2 900  # Engine 2
	param set PWM_MAIN_MIN3 1210  # Elevator R
	param set PWM_MAIN_MIN4 1289  # Mid R
	param set PWM_MAIN_MIN5 1262  # Aileron R
	param set PWM_MAIN_MIN6 1100  # Rudder R

	param set PWM_AUX_MIN1 1000  # Brakes
	param set PWM_AUX_MIN2 1000  # Retraction
	param set PWM_AUX_MIN3 1000  # Trigger
	param set PWM_AUX_MIN4 1000  # Steering servo
	param set PWM_AUX_MIN5 1050  # Elevator L
	param set PWM_AUX_MIN6 1000  # Mid L 
	param set PWM_AUX_MIN7 1057  # Aileron L 
	param set PWM_AUX_MIN8 1100  # Rudder L 

  	param set PWM_MAIN_MAX1 2100  # Engine 1
	param set PWM_MAIN_MAX2 2100  # Engine 2
	param set PWM_MAIN_MAX3 1950  # Elevator R
	param set PWM_MAIN_MAX4 2000  # Mid R
	param set PWM_MAIN_MAX5 1950  # Aileron R
	param set PWM_MAIN_MAX6 1900  # Rudder R

  	param set PWM_AUX_MAX1 2000  # Brakes
	param set PWM_AUX_MAX2 2000  # Retraction
	param set PWM_AUX_MAX3 2000  # Trigger
	param set PWM_AUX_MAX4 2000  # Steering servo
	param set PWM_AUX_MAX5 1728  # Elevator L
	param set PWM_AUX_MAX6 1710  # Mid L
	param set PWM_AUX_MAX7 1739  # Aileron L
	param set PWM_AUX_MAX8 1900  # Rudder L

	# Disarmed PWM outputs
	param set PWM_MAIN_DIS1 900	 	# Engine 1
	param set PWM_MAIN_DIS2 900  	# Engine 2
    param set PWM_MAIN_DIS3 1468    # Elevator R
    param set PWM_MAIN_DIS4 1548    # Mid R
    param set PWM_MAIN_DIS5 1432    # Aileron R
    param set PWM_MAIN_DIS6 1500    # Rudder R
    param set PWM_MAIN_DIS7 1500    # Unused
    param set PWM_MAIN_DIS8 1500    # Unused

    param set PWM_AUX_DIS1 900     # Brakes (no brakes)
	param set PWM_AUX_DIS2 2000    # Retraction (Gear down)
 	param set PWM_AUX_DIS3 1500    # Arduino PWM
	param set PWM_AUX_DIS4 1500    # Servo: centered (steering)
	param set PWM_AUX_DIS5 1468    # Servo: centered
	param set PWM_AUX_DIS6 1458    # Servo: centered
	param set PWM_AUX_DIS7 1478    # Servo: centered
	param set PWM_AUX_DIS8 1500    # Servo: centered

	# Failsafe PWM outputs
	param set PWM_MAIN_FAIL1 900   # ESC: off
	param set PWM_MAIN_FAIL2 900   # ESC: off
	param set PWM_MAIN_FAIL3 1468  # Servo: centered
	param set PWM_MAIN_FAIL4 1548  # Servo: centered
	param set PWM_MAIN_FAIL5 1432  # Servo: centered
    param set PWM_MAIN_FAIL6 1500  # Servo: centered
    param set PWM_MAIN_FAIL7 1500  # Unused
    param set PWM_MAIN_FAIL8 1500  # Unused

	param set PWM_AUX_FAIL1 1500  # Brakes: 50%
	param set PWM_AUX_FAIL2 2000  # Retraction: gear down
	param set PWM_AUX_FAIL3 1350  # FAST_MODE to get the most data through telemetry
	param set PWM_AUX_FAIL4 1465  # Steering: centered
	param set PWM_AUX_FAIL5 1468  # Servo: centered
	param set PWM_AUX_FAIL6 1458  # Servo: centered
	param set PWM_AUX_FAIL7 1478  # Servo: centered
	param set PWM_AUX_FAIL8 1500  # Servo: centered

	# PWM rate
	param set PWM_RATE 100        # Refresh rate in Hz
    param set PWM_AUX_RATE 100    # Refresh rate in Hz

    # Fine trims
    param set PWM_AUX_TRIM4 -0.05 # Nose gear trim


    # ----------------------------------------------------
	#		 			USER PARAMETERS
	# ----------------------------------------------------

	# MAP CONTROL CHANNELS
	param set RC_MAP_THROTTLE 1
	param set RC_MAP_ROLL 2
	param set RC_MAP_PITCH 3
	param set RC_MAP_YAW 4

	# MAP AUXILIARY CHANNELS 
	param set RC_MAP_FLTMODE 6 	# Flight mode switch
	param set RC_MAP_ARM_SW 7  	# Arming switch
	param set RC_MAP_AUX1 9   	# Wheel brakes dial
	param set RC_MAP_AUX2 5 	# Gear retraction switch
	param set RC_MAP_AUX3 8 	# Trigger switch to Arduino/Aeroprobe
	param set RC_MAP_FLAPS 10	# Airbrakes dial (mapped to flaps channel)

    # MAP PARAMETERS TO RC INPUTS
    param set RC_MAP_PARAM1 11	# Knob to tune the yaw damper rate gain
    param set RC_MAP_PARAM2 12  # Knob to tune the yaw damper feedfoward gain

    # SELECT ARDUINO CHANNEL (AUX1, AUX2, or AUX3)
    param set ARDUINO_AUX_CH 3 # Auxiliary channel for Arduino

    # DISABLE UNUSED CHANNELS
    param set RC_MAP_MODE_SW 0	# do not use

	# FLIGHT MODES
	param set COM_FLTMODE1 0 	# Manual
	param set COM_FLTMODE4 8 	# Stabilized/Yaw damper
	param set COM_FLTMODE6 5 	# Return

    # YAW DAMPER
    param set YAW_DAMP_FLAG 1   # 0 = disabled, 1 = enabled (in stabilized mode)
    param set FW_AIRSPD_TRIM 30 # Trim airspeed, used for the scaler
    param set FW_AIRSPD_MIN 25  # Minimum airspeed (should we raise it?)
    param set FW_AIRSPED_MAX 40 # Should we change the parameter definition to
    # increase the max airspeed?

	# BATTERY ESTIMATOR
	param set BAT_N_CELLS 3 		# 3S (11.1 V)
	param set BAT_A_PER_V 65.02386	# Amps-per-volt (Mauch sensor)
	param set BAT_V_DIV 19.12569	# Voltage divider (Mauch sensor)
	param set BAT_V_CHARGED 4.2 	# Full voltage per cell 
	param set BAT_V_EMPTY 3.2 		# Empty voltage per cell (conservative, 3.0 V real value)

    # MANEUVER SETTINGS
    param set MAN_TX_ABORT 0.1

    # PARKING BRAKES
    param set PARK_BRAKES_THR 0.05
    param set PARK_BRAKES_LVL 0.2

	# CALIBRATION PARAMETERS (TO BE REMOVED/CHANGED)
	# param set SYS_HAS_MAG 0
	# param set CAL_MAG0_EN 0
	# param set CAL_MAG1_EN 0
	# param set COM_ARM_MAG 0.5
	# param set CBRK_GPSFAIL 240024
    param set CBRK_IO_SAFETY 22027 # disable safety switch
	# param set CBRK_AIRSPD_CHK 162128
	# param set CBRK_SUPPLY_CHK 894281
	# param set CBRK_FLIGHTTERM 12121
	# param set CBRK_USB_CHK 197848
	# param set CBRK_BUZZER 782097

fi

# Set MAV_TYPE (1 = std plane)
set MAV_TYPE 1

set MIXER flyingV
set MIXER_AUX flyingV

# Set PWM channels
set PWM_OUT 12345678
set PWM_AUX_OUT 12345678
