#!/bin/sh
#
# @name Donkey
#
# @type Standard plane
# @class Plane
#
# @output MAIN1 motor 1
# @output MAIN2 elevator
# @output MAIN3 aileron_R
# @output MAIN4 aileron L
# @output MAIN5 rudder 
# @output MAIN6 empty 
# @output MAIN7 empty
# @output MAIN8 empty
#
# @output AUX1 arduino pwm 
# @output AUX2 empty
# @output AUX3 empty
# @output AUX4 empty 
# @output AUX5 empty 
# @output AUX6 empty 
# @output AUX7 empty 
# @output AUX8 empty 

set VEHICLE_TYPE fw

if [ $AUTOCNF = yes ]
then

	# ----------------------------------------------------
	#		 Default parameters for fixed wing UAVs.
	# ----------------------------------------------------
	param set COM_POS_FS_DELAY 5 	# Time grom GPS loss until failsafe is enabled
	param set COM_POS_FS_EPH 25
	param set COM_POS_FS_EPV 50
	param set COM_POS_FS_GAIN 0
	param set COM_POS_FS_PROB 1
	param set COM_VEL_FS_EVH 5
	param set COM_POSCTL_NAVL 0	 	# RC control after failsafe (1 = no RC control)

	# Kalman filter tuning gains
	param set EKF2_ARSP_THR 8
	param set EKF2_FUSE_BETA 1
	param set EKF2_GPS_CHECK 21
	param set EKF2_MAG_ACCLIM 0
	param set EKF2_MAG_YAWLIM 0
	param set EKF2_REQ_EPH 10
	param set EKF2_REQ_EPV 10
	param set EKF2_REQ_HDRIFT 0.5
	param set EKF2_REQ_SACC 1
	param set EKF2_REQ_VDRIFT 1.0 

	# CHECK! 
	param set RTL_RETURN_ALT 100   # Return altitude
	param set RTL_DESCEND_ALT 100  # Descent altitude
	param set RTL_LAND_DELAY -1    # No land (loiter)

	# FW uses L1 distance for acceptance radius.
	# Set a smaller NAV_ACC_RAD for vertical acceptance distance.
	param set NAV_ACC_RAD 10    # Acceptance radius for waypoints
	param set NAV_LOITER_RAD 100 # Loiter radius

 	# Mission parameters
	param set MIS_LTRMIN_ALT 30  # Minimum loiter altitude 
	param set MIS_TAKEOFF_ALT 25 # Minimum takeoff altitude (for auto?)

	# FW takeoff acceleration can easily exceed ublox GPS 2G default.
	param set GPS_UBX_DYNMODEL 8
	
	# Geofence and failsafe
	param set GF_SOURCE 1 # GPS (independent of position estimation errors)
	param set GF_ACTION 1 # 1 = Warning 3 = Return mode
	param set GF_MAX_HOR_DIST 1500 # Maximum horizontal distance from home
	param set GF_MAX_VER_DIST 130 # Maximum vertical distance from home

	# ----------------------------------------------------
	#		 			PWM SETTINGS
	# ----------------------------------------------------
	# Individual limits
	param set PWM_MAIN_MIN1 900   # Engine 1
	param set PWM_MAIN_MIN2 1150  # Elevator
	param set PWM_MAIN_MIN3 970  # Aileron R
	param set PWM_MAIN_MIN4 1150  # Aileron L
	param set PWM_MAIN_MIN5 1100  # Rudder

	param set PWM_AUX_MIN1 1000  # Arduino PWM 

  	param set PWM_MAIN_MAX1 2100  # Engine
	param set PWM_MAIN_MAX2 1950  # Elevator
	param set PWM_MAIN_MAX3 1830  # Aileron R
	param set PWM_MAIN_MAX4 2000  # Aileron L
	param set PWM_MAIN_MAX5 1900  # Rudder

  	#param set PWM_AUX_MAX1 2000  # Arduino PWM

	# Disarmed PWM outputs
	param set PWM_DISARMED 1500
	param set PWM_MAIN_DIS1 900	 	# Engine 1
	param set PWM_AUX_DISARMED 1500

	# Failsafe PWM outputs
	param set PWM_MAIN_FAIL1 900   # ESC: off
	param set PWM_MAIN_FAIL2 1500  # Servo: centered
	param set PWM_MAIN_FAIL3 1500  # Servo: centered
	param set PWM_MAIN_FAIL4 1500  # Servo: centered
	param set PWM_MAIN_FAIL5 1500  # Servo: centered

	#param set PWM_AUX_FAIL1 900   # Arduino PWM

	# Channel reversal
	param set PWM_MAIN_REV3 1
	param set PWM_MAIN_REV4 1
	param set PWM_MAIN_REV5 1
	# PWM rate
	param set PWM_RATE 100        # Refresh rate in Hz	
	param set PWM_AUX_RATE 100    # Refresh rate in Hz	
	# ----------------------------------------------------
	#		 			USER PARAMETERS
	# ----------------------------------------------------
	
	# MAP CONTROL CHANNELS 
	param set RC_MAP_THROTTLE 1
	param set RC_MAP_ROLL 2
	param set RC_MAP_PITCH 3
	param set RC_MAP_YAW 4

	# MAP AUXILIARY CHANNELS
    param set RC_MAP_FLAPS 0	
	param set RC_MAP_FLTMODE 5 	# Flight mode switch
	param set RC_MAP_ARM_SW 6  	# Arming switch
	#param set RC_MAP_AUX1 7   	# Arduino PWM
	#param set RC_MAP_PARAM 7	# Safety switch for automatic maneuvers
    

    # DISABLE UNUSED CHANNELS
    param set RC_MAP_MODE_SW 0	# do not use 
	param set RC_MAP_PARAM2 0	# Do we need to set any parameter with a dial? 

	# FLIGHT MODES
	param set COM_FLTMODE1 0 	# Manual 
	param set COM_FLTMODE4 8 	# Stabilized
	param set COM_FLTMODE6 5 	# Return 

	# BATTERY ESTIMATOR
	param set BAT_N_CELLS 3 		# 3S (11.1 V)
	#param set BAT_A_PER_V 65.02386	# Amps-per-volt (Mauch sensor)
	#param set BAT_V_DIV 19.12569	# Voltage divider (Mauch sensor)
	param set BAT_V_CHARGED 4.2 	# Full voltage per cell 
	param set BAT_V_EMPTY 3.2 		# Empty voltage per cell (conservative, 3.0 V real value)

    # AUTOMATED MANEUVER SETTINGS 
    param set MAN_TX_ABORT 0.1

	# AIRFRAME
	#param set CAL_MAG0_ROT 8
	# CALIBRATION PARAMETERS (TO BE REMOVED/CHANGED)
	# param set SYS_HAS_MAG 0
	# param set CAL_MAG0_EN 0
	# param set CAL_MAG1_EN 0
	# param set COM_ARM_MAG 0.5
	# param set CBRK_GPSFAIL 240024
	# param set CBRK_IO_SAFETY 22027
	# param set CBRK_AIRSPD_CHK 162128
	# param set CBRK_SUPPLY_CHK 894281
	# param set CBRK_FLIGHTTERM 12121
	# param set CBRK_USB_CHK 197848
	# param set CBRK_BUZZER 782097

fi

# SELECT ARDUINO CHANNEL (AUX1, AUX2, or AUX3)
param set ARDUINO_AUX_CH 1 # Auxiliary channel for Arduino

# Set MAV_TYPE (1 = std plane)
set MAV_TYPE 1

set MIXER donkey
set MIXER_AUX donkey

# Set PWM channels
set PWM_OUT 12345
set PWM_AUX_OUT 123
